### ISSUE TITLE
Android X的相关问题

### ISSUE THREAD

**Issue by kotlings** [Sky24n/flutter_wanandroid#88]
Android X和support 兼容问题

**Comment by Sky24n** [comment]
日志呢

**Comment by MartinDong** [comment]
```log
Launching lib\main.dart on OS105 in debug mode...
I/flutter ( 6602): ###common_utils###   e   ReposPage build......
I/flutter ( 6602): ###common_utils###   e   onRefresh labelId: str_title_repos   _reposPage: 0
I/flutter ( 6602): ###common_utils###   e   HotPage build......
I/flutter ( 6602): ###common_utils###   e   HotPage init......
I/flutter ( 6602): ###common_utils###   e   onRefresh labelId: str_title_hot   _reposPage: 0
I/flutter ( 6602): ###common_utils###   e   getJueJinHotList...  10
I/flutter ( 6602): ###common_utils###   e   EventsPage build......
I/flutter ( 6602): ###common_utils###   e   EventsPage init......
I/flutter ( 6602): ###common_utils###   e   ===============EventsPage hasData: false , hasError: false, error: null
I/flutter ( 6602): ###common_utils###   e   onRefresh labelId: str_title_events   _reposPage: 0
I/flutter ( 6602): ###common_utils###   e   ===============EventsPage hasData: true , hasError: false, error: null
I/flutter ( 6602): ###common_utils###   e   onLoadMore labelId: str_title_hot   _page: 2   _reposPage: 0
I/flutter ( 6602): ###common_utils###   e   getJueJinHotList...  20
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Running Gradle task 'assembleDebug'...
I/flutter ( 7199): ###common_utils###   e   MainBloc......
I/flutter ( 7199): ###common_utils###   e   message: Bugly 初始化成功, isSuccess: true
I/flutter ( 7199): ###common_utils###   e   ----------------equal-------------
I/flutter ( 7199): ###common_utils###   e   HomePage build......
I/flutter ( 7199): ###common_utils###   e   ReposPage build......
I/flutter ( 7199): ###common_utils###   e   onRefresh labelId: str_title_home   _reposPage: 0
I/flutter ( 7199): ###common_utils###   e   onRefresh labelId: str_title_repos   _reposPage: 0
I/flutter ( 7324): ###common_utils###   e   MainBloc......
I/flutter ( 7324): ###common_utils###   e   message: Bugly 初始化成功, isSuccess: true
I/flutter ( 7324): ###common_utils###   e   ----------------equal-------------
I/flutter ( 7324): ###common_utils###   e   HomePage build......
I/flutter ( 7324): ###common_utils###   e   onRefresh labelId: str_title_home   _reposPage: 0
I/flutter ( 7416): ###common_utils###   e   MainBloc......
I/flutter ( 7416): ###common_utils###   e   message: Bugly 初始化成功, isSuccess: true
I/flutter ( 7416): ###common_utils###   e   ----------------equal-------------
I/flutter ( 7416): ###common_utils###   e   HomePage build......
I/flutter ( 7416): ###common_utils###   e   onRefresh labelId: str_title_home   _reposPage: 0
I/flutter ( 7810): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter ( 7810): The following assertion was thrown while dispatching notifications for FocusNode:
I/flutter ( 7810): RenderBox was not laid out: RenderEditable#4bfa4 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7810): 'package:flutter/src/rendering/box.dart':
I/flutter ( 7810): Failed assertion: line 1687 pos 12: 'hasSize'
I/flutter ( 7810): 
I/flutter ( 7810): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7810): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7810): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7810):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 7810): 
I/flutter ( 7810): When the exception was thrown, this was the stack:
I/flutter ( 7810): #2      RenderBox.size (package:flutter/src/rendering/box.dart:1687:12)
I/flutter ( 7810): #3      EditableTextState._updateSizeAndTransform (package:flutter/src/widgets/editable_text.dart:1729:40)
I/flutter ( 7810): #4      EditableTextState._openInputConnection (package:flutter/src/widgets/editable_text.dart:1415:7)
I/flutter ( 7810): #5      EditableTextState._openOrCloseInputConnectionIfNeeded (package:flutter/src/widgets/editable_text.dart:1441:7)
I/flutter ( 7810): #6      EditableTextState._handleFocusChanged (package:flutter/src/widgets/editable_text.dart:1707:5)
I/flutter ( 7810): #7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
I/flutter ( 7810): #8      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:808:5)
I/flutter ( 7810): #9      FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1401:12)
I/flutter ( 7810): (elided 12 frames from class _AssertionError and package dart:async)
I/flutter ( 7810): 
I/flutter ( 7810): The FocusNode sending notification was:
I/flutter ( 7810):   FocusNode#fe9e0
I/flutter ( 7810): ════════════════════════════════════════════════════════════════════════════════════════════════════
D:\Code\flutter_project\flutter_wanandroid\android\app\src\main\AndroidManifest.xml:22:18-91 Error:
	Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:16:5-39:19 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:16:5-39:19 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
AndroidX incompatibilities may have caused this build to fail. Please migrate your app to AndroidX. See https://goo.gl/CP92wY.
Finished with error: Gradle task assembleDebug failed with exit code 1



```
